language: node_js
node_js:
  - 12

install:
  - npm install

script:
  - hexo g
  - git submodule init
  - git submodule update

after_script:
  - cd ./public
  - git init
  - git config user.name "Gsealy"
  - git config user.email "jiaojingwei1001@hotmail.com"
  - git add .
  - git commit -m "Push Post"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/Gsealy/gsealy.github.io.git